#!/bin/sh

echo "Post checkout hook executed"

for sd in */ ; do
	f="${sd}.git"
	echo "Folder ${sd}"
	
	if [ -f "$f" ]; then
		echo "Removing ${sd} submodule"
		rm -rf $sd
	fi
done

echo "Updating submodules"
git submodule update --init --recursive